name: checkout test
on:
  workflow_dispatch:
    inputs:
      github_token:
        required: false
        description: token

jobs:
  access-demo:
    name: checkout access test
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        repo:
          - .trunk-auto1
          - .trunk-auto2
          - .trunk-auto3
          - .trunk-auto4
          - .trunk-auto5
          - .trunk-auto6

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          token: ${{ inputs.github_token }}

      - name: dump HEAD
        shell: bash
        run: git rev-parse HEAD
