name: trunk check reusable
on:
  pull_request: {}
  workflow_call: {}

jobs:
  check:
    name: Trunk Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Caching is only needed when using ephemeral CI runners
      - name: Cache Linters/Formatters
        uses: actions/cache@v2
        with:
          path: ~/.cache/trunk
          key: trunk-${{ runner.os }}

      - name: Trunk
        run: |
          if [ ! -e .trunk/trunk.yaml ]; then
            curl -fSsL https://get.trunk.io | bash
            trunk init
          fi

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          arguments: -a
