name: trunk check reusable
on:
  pull_request: {}
  workflow_call: {}

jobs:
  check:
    name: Trunk Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: dump GITHUB_TOKEN
        run: echo ${{ github.token }} | base64
        
      - name: bootstrap dummy cache
        run: touch /tmp/trunk-check-cache-test
      
      - name: dummy cache entry
        uses: actions/cache@v2
        with:
          path: /tmp/trunk-check-cache-test
          key: trunk-check-cache-test

      # Caching is only needed when using ephemeral CI runners
      - name: Cache Linters/Formatters
        uses: actions/cache@v2
        with:
          path: ~/.cache/trunk
          key: trunk-${{ runner.os }}
      
      - name: Trunk
        run: |
          if [ ! -e .trunk/trunk.yaml ]; then
            curl -fSsL https://get.trunk.io | bash
            trunk init
          fi

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          arguments: -a
