name: Pull Request
on: [pull_request]

jobs:
  trunk_check_runner:
    name: Trunk Check runner [linux]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Caching is only needed when using ephemeral CI runners
      - name: Cache Linters/Formatters
        uses: actions/cache@v2
        with:
          path: ~/.cache/trunk
          key: trunk-${{ runner.os }}

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
